services:
  - type: web
    name: yt-downloader-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: pip install -U yt-dlp && chmod +x build.sh && ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000